export const newProduct = [
  {
    category: "Fruits",
    items: [
      {
        name: "Orange",
        img: "https://w7.pngwing.com/pngs/1001/506/png-transparent-slices-of-oranges-orange-juice-flavor-fruit-nutritious-orange-natural-foods-food-orange-thumbnail.png",
        id: 1,
        price: 2.99,
        total: 2.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.6,
        reviewCount: 22,
      },
      {
        name: "Water Melon",
        img: "https://w7.pngwing.com/pngs/389/21/png-transparent-sliced-of-watermelon-seedless-fruit-sun-melon-juice-watermelon-natural-foods-food-melon-thumbnail.png",
        id: 2,
        price: 4.99,
        total: 4.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.8,
        reviewCount: 25,
      },
      {
        name: "Strawberry",
        img: "https://w7.pngwing.com/pngs/102/28/png-transparent-strawberry-juice-fruit-smoothie-strawberry-fruit-natural-foods-frutti-di-bosco-food-thumbnail.png",
        id: 3,
        price: 3.99,
        total: 3.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.8,
        reviewCount: 28,
      },
      {
        name: "Banana",
        img: "https://w7.pngwing.com/pngs/675/836/png-transparent-banana-juice-cavendish-banana-fruit-eating-delicious-delicious-banana-food-tropical-fruit-eating-thumbnail.png",
        id: 4,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "coconut",
        img: "https://w7.pngwing.com/pngs/694/675/png-transparent-coconut-milk-coconut-water-nata-de-coco-coconut-oil-coconut-coconut-fruit-illustration-natural-foods-food-eating-thumbnail.png",
        id: 5,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "papaya",
        img: "https://w7.pngwing.com/pngs/551/716/png-transparent-papain-dietary-supplement-papaya-powder-enzyme-papaya-food-nutrition-green-papaya-thumbnail.png",
        id: 6,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "pineapple",
        img: "https://w7.pngwing.com/pngs/238/575/png-transparent-pineapple-juice-smoothie-cocktail-pineapple-juice-juice-dried-fruit-food-fruit-thumbnail.png",
        id: 7,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "pomegranate",
        img: "https://w7.pngwing.com/pngs/702/804/png-transparent-pomegranate-pomegranate-juice-fruit-pomegranate-natural-foods-frutti-di-bosco-food-thumbnail.png",
        id: 8,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "apple",
        img: "https://w7.pngwing.com/pngs/950/365/png-transparent-apple-icon-cut-apple-natural-foods-food-green-apple-thumbnail.png",
        id: 9,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "dragon",
        img: "https://w7.pngwing.com/pngs/203/1019/png-transparent-sliced-dragon-fruit-juice-hylocereus-undatus-hylocereus-megalanthus-pitaya-fruit-durian-natural-foods-food-nutrition-thumbnail.png",
        id: 10,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "black Grapes",
        img: "https://w7.pngwing.com/pngs/118/148/png-transparent-red-wine-common-grape-vine-muscadine-grape-fresh-purple-grapes-purple-natural-foods-food-thumbnail.png",
        id: 11,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "Grapes",
        img: "https://w7.pngwing.com/pngs/997/412/png-transparent-bunch-of-white-grapes-muscat-wine-juice-concord-grape-grape-natural-foods-food-wine-thumbnail.png",
        id: 12,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "guava",
        img: "https://w7.pngwing.com/pngs/429/705/png-transparent-common-guava-nutrition-facts-label-jam-food-biji-natural-foods-tropical-fruit-nutrition-thumbnail.png",
        id: 13,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "avocado",
        img: "https://w7.pngwing.com/pngs/990/7/png-transparent-hass-avocado-fruit-health-vegetable-fat-avocado-natural-foods-food-citrus-thumbnail.png",
        id: 14,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "blueberries",
        img: "https://w7.pngwing.com/pngs/97/557/png-transparent-blueberry-muffin-blueberries-food-antioxidant-fruit-thumbnail.png",
        id: 15,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "raspberries",
        img: "https://w7.pngwing.com/pngs/801/111/png-transparent-raspberries-raspberry-juice-raspberry-juice-fruit-raspberry-pattern-natural-foods-frutti-di-bosco-food-thumbnail.png",
        id: 16,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "cherry",
        img: "https://w7.pngwing.com/pngs/971/975/png-transparent-sour-cherry-cherry-natural-foods-frutti-di-bosco-food-thumbnail.png",
        id: 17,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "galia-melon",
        img: "https://w7.pngwing.com/pngs/84/218/png-transparent-galia-melon-cantaloupe-honeydew-canary-melon-melon-food-sweetness-melon-thumbnail.png",
        id: 18,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "Green Apple",
        img: "https://w7.pngwing.com/pngs/46/928/png-transparent-juice-smoothie-apple-green-flavor-fresh-green-apple-fruit-green-apple-natural-foods-blue-food-thumbnail.png",
        id: 19,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "Kiwi",
        img: "https://w7.pngwing.com/pngs/945/573/png-transparent-kiwi-fruit-illustration-juice-smoothie-kiwifruit-kiwi-natural-foods-food-citrus-thumbnail.png",
        id: 20,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
    ],
  },
];
