export const newProduct = [
  {
    category: "Vegetables",
    items: [
      {
        name: "Coriander",
        img: "https://w7.pngwing.com/pngs/867/336/png-transparent-dish-herb-parsley-root-vegetable-food-vegetable-leaf-vegetable-dried-fruit-superfood-thumbnail.png",
        id: 1,
        price: 2.99,
        total: 2.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.6,
        reviewCount: 22,
      },
      {
        name: "Brenjail",
        img: "https://w7.pngwing.com/pngs/113/468/png-transparent-eggplant-baingan-bharta-tomato-vegetables-purple-natural-foods-image-file-formats-thumbnail.png",
        id: 2,
        price: 4.99,
        total: 4.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.8,
        reviewCount: 25,
      },
      {
        name: "Onion",
        img: "https://w7.pngwing.com/pngs/1023/22/png-transparent-red-onion-yellow-onion-white-onion-french-onion-soup-onions-natural-foods-food-image-file-formats-thumbnail.png",
        id: 3,
        price: 3.99,
        total: 3.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.8,
        reviewCount: 28,
      },
      {
        name: "Red Onion",
        img: "https://w7.pngwing.com/pngs/504/981/png-transparent-red-onion-vegetable-food-potato-onion-white-onion-vegetable-food-tomato-nutrition-thumbnail.png",
        id: 4,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "Garlic",
        img: "https://w7.pngwing.com/pngs/855/205/png-transparent-garlic-beside-onion-garlic-food-eating-vegetable-garlic-onion-vegetables-shallot-thumbnail.png",
        id: 5,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "Potato",
        img: "https://w7.pngwing.com/pngs/574/312/png-transparent-kennebec-potato-french-fries-potato-image-file-formats-food-vegetables-thumbnail.png",
        id: 6,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "Lemon",
        img: "https://w7.pngwing.com/pngs/711/905/png-transparent-juice-lemon-lemon-natural-foods-food-citrus-thumbnail.png",
        id: 7,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "Spanich",
        img: "https://w7.pngwing.com/pngs/943/1017/png-transparent-cabbage-cauliflower-brussels-sprout-vegetable-seed-cabbage-leaf-vegetable-food-chili-pepper-thumbnail.png",
        id: 8,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "Lady Finger",
        img: "https://w7.pngwing.com/pngs/217/236/png-transparent-lady-finger-vegetable-gumbo-ladyfinger-okra-vegetable-fruit-okra-natural-foods-leaf-vegetable-food-thumbnail.png",
        id: 9,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "Green Peas",
        img: "https://w7.pngwing.com/pngs/985/126/png-transparent-green-peas-snow-pea-organic-food-vegetable-legume-vegetables-natural-foods-food-vegetable-salad-thumbnail.png",
        id: 10,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "Green Chili",
        img: "https://w7.pngwing.com/pngs/588/395/png-transparent-green-chili-chili-pepper-chili-con-carne-vegetarian-cuisine-vegetable-capsicum-fresh-chili-natural-foods-food-cayenne-pepper-thumbnail.png",
        id: 11,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "Red Chili",
        img: "https://w7.pngwing.com/pngs/669/974/png-transparent-three-red-chili-chili-con-carne-cayenne-pepper-chili-pepper-spice-herb-red-pepper-natural-foods-food-cooking-thumbnail.png",
        id: 12,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "Red Chili",
        img: "https://w7.pngwing.com/pngs/669/974/png-transparent-three-red-chili-chili-con-carne-cayenne-pepper-chili-pepper-spice-herb-red-pepper-natural-foods-food-cooking-thumbnail.png",
        id: 13,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "Green biter",
        img: "https://w7.pngwing.com/pngs/861/946/png-transparent-bitter-melon-juice-leaf-vegetable-organic-food-juice-natural-foods-leaf-vegetable-food-thumbnail.png",
        id: 14,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "Green biter",
        img: "https://w7.pngwing.com/pngs/861/946/png-transparent-bitter-melon-juice-leaf-vegetable-organic-food-juice-natural-foods-leaf-vegetable-food-thumbnail.png",
        id: 15,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "Pumpkin",
        img: "https://w7.pngwing.com/pngs/617/442/png-transparent-calabaza-kabocha-pumpkin-halloween-pumpkin-food-gourd-fruit-thumbnail.png",
        id: 16,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "Green Bhaijan",
        img: "https://w7.pngwing.com/pngs/526/442/png-transparent-eggplant-chili-con-carne-baingan-bharta-indian-cuisine-food-green-brinjal-natural-foods-dried-fruit-chili-pepper-thumbnail.png",
        id: 17,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "Red Capciusm",
        img: "https://w7.pngwing.com/pngs/243/869/png-transparent-chili-pepper-capsicum-bell-pepper-pepper-natural-foods-food-tomato-thumbnail.png",
        id: 18,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "Lettuce leaf",
        img: "https://w7.pngwing.com/pngs/18/437/png-transparent-green-lettuce-leaf-vegetable-salad-butterhead-lettuce-iceberg-lettuce-romaine-lettuce-product-food-eating-chili-pepper-thumbnail.png",
        id: 19,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
      {
        name: "Cauiflower",
        img: "https://w7.pngwing.com/pngs/31/763/png-transparent-white-cauliflower-frutti-di-bosco-vegetable-fruit-cauliflower-cauliflower-leaf-vegetable-food-cooking-thumbnail.png",
        id: 20,
        price: 1.99,
        total: 1.99,
        quantity: 1,
        unit: "kg",
        reviews: 4.7,
        reviewCount: 21,
      },
    ],
  },
];
